// Mocks generated by Mockito 5.4.4 from annotations
// in chat_2/test/helper/test_helper.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i3;

import 'package:chat_2/core/error/failures.dart' as _i6;
import 'package:chat_2/features/auth/domin/entites/auth_model/requiest/login_request_entity.dart'
    as _i8;
import 'package:chat_2/features/auth/domin/entites/auth_model/requiest/signup_request_entity.dart'
    as _i10;
import 'package:chat_2/features/auth/domin/entites/auth_model/response/login_response_entity.dart'
    as _i7;
import 'package:chat_2/features/auth/domin/entites/auth_model/response/signup_response_entity.dart'
    as _i9;
import 'package:chat_2/features/auth/domin/entites/image_partner_model/response/image_partner_response.dart'
    as _i11;
import 'package:chat_2/features/auth/domin/repository/auth_repository.dart'
    as _i4;
import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientRequest_2 extends _i1.SmartFake
    implements _i3.HttpClientRequest {
  _FakeHttpClientRequest_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i4.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i7.LoginResponse>> login(
          {required _i8.LoginRequest? loginEntite}) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [],
          {#loginEntite: loginEntite},
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i7.LoginResponse>>.value(
                _FakeEither_0<_i6.Failure, _i7.LoginResponse>(
          this,
          Invocation.method(
            #login,
            [],
            {#loginEntite: loginEntite},
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i7.LoginResponse>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i9.SigninResponse>> signin(
          {required _i10.SigninRequest? signinEntite}) =>
      (super.noSuchMethod(
        Invocation.method(
          #signin,
          [],
          {#signinEntite: signinEntite},
        ),
        returnValue:
            _i5.Future<_i2.Either<_i6.Failure, _i9.SigninResponse>>.value(
                _FakeEither_0<_i6.Failure, _i9.SigninResponse>(
          this,
          Invocation.method(
            #signin,
            [],
            {#signinEntite: signinEntite},
          ),
        )),
      ) as _i5.Future<_i2.Either<_i6.Failure, _i9.SigninResponse>>);

  @override
  _i5.Future<_i2.Either<_i6.Failure, _i11.ImagePartnerResponse>>
      imagePartner() => (super.noSuchMethod(
            Invocation.method(
              #imagePartner,
              [],
            ),
            returnValue: _i5.Future<
                    _i2.Either<_i6.Failure, _i11.ImagePartnerResponse>>.value(
                _FakeEither_0<_i6.Failure, _i11.ImagePartnerResponse>(
              this,
              Invocation.method(
                #imagePartner,
                [],
              ),
            )),
          ) as _i5.Future<_i2.Either<_i6.Failure, _i11.ImagePartnerResponse>>);
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i3.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get idleTimeout => (super.noSuchMethod(
        Invocation.getter(#idleTimeout),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#idleTimeout),
        ),
      ) as Duration);

  @override
  set idleTimeout(Duration? _idleTimeout) => super.noSuchMethod(
        Invocation.setter(
          #idleTimeout,
          _idleTimeout,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set connectionTimeout(Duration? _connectionTimeout) => super.noSuchMethod(
        Invocation.setter(
          #connectionTimeout,
          _connectionTimeout,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set maxConnectionsPerHost(int? _maxConnectionsPerHost) => super.noSuchMethod(
        Invocation.setter(
          #maxConnectionsPerHost,
          _maxConnectionsPerHost,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get autoUncompress => (super.noSuchMethod(
        Invocation.getter(#autoUncompress),
        returnValue: false,
      ) as bool);

  @override
  set autoUncompress(bool? _autoUncompress) => super.noSuchMethod(
        Invocation.setter(
          #autoUncompress,
          _autoUncompress,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userAgent(String? _userAgent) => super.noSuchMethod(
        Invocation.setter(
          #userAgent,
          _userAgent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authenticate(
          _i5.Future<bool> Function(
            Uri,
            String,
            String?,
          )? f) =>
      super.noSuchMethod(
        Invocation.setter(
          #authenticate,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set connectionFactory(
          _i5.Future<_i3.ConnectionTask<_i3.Socket>> Function(
            Uri,
            String?,
            int?,
          )? f) =>
      super.noSuchMethod(
        Invocation.setter(
          #connectionFactory,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set findProxy(String Function(Uri)? f) => super.noSuchMethod(
        Invocation.setter(
          #findProxy,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authenticateProxy(
          _i5.Future<bool> Function(
            String,
            int,
            String,
            String?,
          )? f) =>
      super.noSuchMethod(
        Invocation.setter(
          #authenticateProxy,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set badCertificateCallback(
          bool Function(
            _i3.X509Certificate,
            String,
            int,
          )? callback) =>
      super.noSuchMethod(
        Invocation.setter(
          #badCertificateCallback,
          callback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set keyLog(dynamic Function(String)? callback) => super.noSuchMethod(
        Invocation.setter(
          #keyLog,
          callback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.HttpClientRequest> open(
    String? method,
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #open,
          [
            method,
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #open,
            [
              method,
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> openUrl(
    String? method,
    Uri? url,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #openUrl,
          [
            method,
            url,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #openUrl,
            [
              method,
              url,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> get(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #get,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> getUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #getUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #getUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> post(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #post,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> postUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #postUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #postUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> put(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #put,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> putUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #putUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #putUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> delete(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #delete,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> deleteUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #deleteUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #deleteUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> patch(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #patch,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> patchUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #patchUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #patchUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> head(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #head,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> headUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #headUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #headUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  void addCredentials(
    Uri? url,
    String? realm,
    _i3.HttpClientCredentials? credentials,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addCredentials,
          [
            url,
            realm,
            credentials,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addProxyCredentials(
    String? host,
    int? port,
    String? realm,
    _i3.HttpClientCredentials? credentials,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addProxyCredentials,
          [
            host,
            port,
            realm,
            credentials,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );
}
